
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend/database.db:/code/database.db
      - ./backend/gameLogs:/code/gameLogs
    ports:
      - "4000:4000"
      - "8001-8020:8001-8020" 
  


